config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  user_options =
    {
      only: [:show],
      param: :slug,
      controller: 'users',
      constraints: { slug: /[A-Za-z0-9\-\_]*/ }
    }

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :user, user_options do
    resources :patch, only: [:show], param: :slug, controller: 'patches'
    resources :keys_patch,
              only: [:show, :edit],
              param: :slug,
              controller: 'keys/patches',
              path: 'keys/patch'
  end

  resources :patch, param: :id, controller: 'patches', except: [:index]
  get 'bass/emulator' => 'emulators#new', as: :bass_emulator
  get 'keys/emulator' => 'emulators#new_keys', as: :keys_emulator
  get 'synth_patch_namer' => 'synth_patch_namers#show'
  get 'synth_patch_name' => 'synth_patch_namers#name'
  post 'patch' => 'patches#create'
  resources :patches, only: [:index]
  get 'about' => 'welcome#index'
  resources :contacts, only: [:new, :create]
  match 'tags/show' => 'tags#show', via: :get
  match 'oembed' => 'patches#oembed', via: :get

  namespace 'keys' do
    resources :patch,
              controller: 'patches',
              only: [:new, :show, :update, :destroy],
              param: :id
    resources :patches, only: [:index]
    post 'patch' => 'patches#create'
    match 'tags/show' => 'tags#show', via: :get
    match 'oembed' => 'patches#oembed', via: :get
  end

  root 'welcome#index'

  unless Rails.application.config.consider_all_requests_local
    # Return 404 for all non-conforming paths
    get '*path', to: 'errors#not_found', via: :all
  end
end

app/views/shared/_audio_preview.html.haml
#audio-preview-modal.modal.fade{"aria-labelledby" => "audioPreviewModaLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#audioPreviewModaLabel.modal-title
      #preview-modal-body.modal-body
        = image_tag 'loading.gif', class: 'loading'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: 'button'} Dismiss
        =link_to 'Go to Patch', '#', id: 'go-to-patch', class: 'btn btn-primary'

app/views/shared/_audio_sample.html.haml
#audio-sample-button{ data: {toggle: 'modal', target: '#audio-sample-modal'}}
#audio-sample-modal.modal.fade{"aria-labelledby" => "audioSampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#audioSampleModalLabel.modal-title Audio sample
      .modal-body
        %p
          Enter the full URL of the sound on YouTube, SoundCloud or Freesound.org.  The sound will be automatically embedded on the patch page after you submit the form.  Only one audio sample is allowed per patch.
          %br/
          %br/
          Examples:
          %ul
            %li https://www.youtube.com/watch?v=PxKC9jhuA3k
            %li https://soundcloud.com/volcashare/vacation-patch-1
            %li http://www.freesound.org/people/orangefreesounds/sounds/261094/
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Dismiss

app/views/shared/_cookies_banner.html.haml
- if !cookie_consent_given?
  #cookie-banner{ class: "alert alert-info", style: "position: fixed; bottom: 0; width: 100%; text-align: center; margin-bottom: 0;" }
    %p
      VolcaShare uses cookies for the "keep me logged in" feature.  There are no tracking or marketing cookies of any kind.
      %button{ class: "btn btn-primary", onclick: "acceptCookies()" } OK

app/views/shared/_footer.html.haml
%footer.footer
  .container.text-muted
    %span.glyphicon.glyphicon-copyright-mark
    ="#{Time.now.year} VolcaShare  |  #{link_to 'Contact', new_contact_path}"
    %br/
    .small
      This application is not affiliated with Korg Inc. or any related business entities.  The use of the Korg and Volca Bass and Volca Keys logos and layout are in reference to the products and do not constitute any approval or endorsement of VolcaShare by Korg.

app/views/shared/_keys_emulator_callout_modal.html.haml
- keys_callout_feature_on = ENV['FEATURE_ENABLED_KEYS_EMULATOR_CALLOUT'] == 'true'
- cookie_not_set = cookies[:keysEmulatorCalloutSeen] != 'true'
- on_keys_emulator_page = current_page?(keys_emulator_path)
- if keys_callout_feature_on && cookie_not_set && !on_keys_emulator_page
  - if Rails.env.production?
    :javascript
      ga('send', 'event', 'modal', 'view', 'keys_emulator_callout_modal', 1);
  %button#keys-callout-button.hidden{ type: "button", class: "btn btn-primary btn-lg", data: { toggle: "modal", target: "#keys-emulator-callout-modal" } }
    Launch demo modal

  #keys-emulator-callout-modal.modal.fade{"aria-labelledby" => "keysEmulatorCalloutModaLabel", :role => "dialog", :tabindex => "-1", :data => { show: 'true' }}
    .modal-dialog{:role => "document"}
      .modal-content
        .modal-header
          %button#kem-x-out.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
            %span{"aria-hidden" => "true"} ×
          %h2#keysEmulatorCalloutModaLabel.modal-title
            🎉 Introducing the Volca&nbsp;Keys&nbsp;Emulator!
        #keys-emulator-callout-modal-body.modal-body
          =link_to keys_emulator_path, id: 'kem-image' do
            #banner
          %p
            Play notes, tweak parameters, and explore the sound design features of the Volca Keys directly in your web browser.  No hardware necessary.
        .modal-footer
          %button#kem-close.btn.btn-default{"data-dismiss" => "modal", type: 'button'} Close
          =link_to 'Try it now', keys_emulator_path, class: 'btn btn-primary', id: 'kem-try-it-now'

app/views/shared/_keys_patch_card.html.haml
- wrapper_class ||= ''
.wrapper.well.well-sm.patch-holder{ class: wrapper_class }
  .image-holder
    - if patch.user.present?
      = link_to user_keys_patch_path(patch.user.slug, patch.slug), { class: :title } do
        .image.keys{ class: patch.index_classes }
    - else
      = link_to keys_patch_path(patch.id), { class: :title } do
        .image.keys{ class: patch.index_classes }
  .patch
    - if patch.secret?
      .lock.glyph{ title: 'Secret' }
    - if patch.audio_sample_available?
      .speaker{ data: { oembed_url: "/keys/oembed?user_slug=#{patch.user.slug}&slug=#{patch.slug}", toggle: 'modal', target: '#audio-preview-modal' }, title: 'Preview audio' }
    .title
      - if patch.user.present?
        = link_to patch.name, user_keys_patch_path(patch.user.slug, patch.slug), { class: :title }
      - else
        = link_to patch.name, keys_patch_path(patch.id), { class: :title }
    .info
      by
      - if patch.user.present?
        = link_to patch.user&.username, user_path(patch.user&.slug), { class: :username }
      - else
        ¯\_(ツ)_/¯
      %span.date= "on #{patch.created_at.strftime("%B %-d, %Y" )}"
      .icons
        - if current_user.present? && patch.user == current_user
          = link_to edit_user_keys_patch_path(current_user.slug, patch.slug) do
            .edit.glyph
          = form_tag keys_patch_path(patch.id), method: :delete, class: :delete_form, data: { confirm: 'Are you sure you want to delete that patch?' } do
            = submit_tag 'Delete', class: 'delete glyph'
    .description= patch.notes
    .tags
      - patch.tags.each do |tag|
        = link_to "\##{tag}", keys_tags_show_path(tag: tag), class: :tag

app/views/shared/_keys_patches.html.haml
- locals ||= {}
- if @keys_patches.empty?
  .well No patches to show.
- else
  .col-sm-12.clearfix
    - unless locals[:hide_pagination]
      .pagination-holder.col-sm-6
        = paginate @keys_patches
    .sort.col-sm-6
      - if @sort.present?
        .h4
          Sort by:
          - if @sort == :quality
            = link_to 'Date Created', keys_patches_path(sort: :newest)
          - else
            Date Created
          &nbsp;|&nbsp;
          - if @sort == :created_at
            = link_to 'Quality', keys_patches_path
          - else
            Quality

  - @keys_patches.each do |patch|
    = render partial: 'shared/keys_patch_card', locals: { patch: patch, wrapper_class: 'col-md-6' }

  .col-sm-12.clearfix
    - unless locals[:hide_pagination]
      .pagination-holder.col-sm-6
        = paginate @keys_patches

app/views/shared/_midi_button.html.haml
- button_text ||= nil
.btn.btn-primary#enable-web-midi{ data: {toggle: 'modal', target: '#web-midi-modal'}}= button_text || 'Enable Web MIDI Out'
#web-midi-modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Enabling Wed Midi (Chrome 43+ only)
      .modal-body
        %p To control your Volca directly from the browser, connect and enable a device capable of MIDI output, such as an audio interface, to your computer or other browsing device.  It will be detected by the browser when you reload.
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Dismiss

app/views/shared/_midi_control.html.haml
#midi-output.hidden
  .well
    %h3 Midi output
    %select.form-control#midi-device
    %select.form-control#midi-channel
      %option Midi Channel
      - (1..16).each do |number|
        %option{value: number}= "Channel #{number}"
    %span#channel-tooltip.btn.btn-info{ data: {toggle: 'modal', target: '#channel-modal'}} ?
    #channel-modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"}
            %h4#myModalLabel.modal-title What channel is my Volca on?
          .modal-body
            %p To find or set the MIDI channel of your Volca:
            %ol
              %li Power off the Volca.
              %li While holding down the MEMORY button, turn on the Volca Bass.
              %li Step buttons 1 to 16 correspond to the MIDI channels 1 to 16.  Press the button that corresponds to the desired channel, and the LED below the step button will light up.
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Dismiss
    * Controls outlined in green can be controlled via the browser.
    #sync-button-container
      %button.btn.btn-primary#sync.disabled{ data: {toggle: 'modal', target: '#sync-modal'}} Sync
      .green-check-mark
    #sync-modal.modal.fade{"aria-labelledby" => "mySyncModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
            %h4#mySyncModalLabel.modal-title Patch synced
          .modal-body
            %p Controls outlined in green have been sent to your Volca.  Please adjust the non-highlighted parameters manually on the physical Volca machine.
          .modal-footer
            #dont-show-again-container
              = check_box_tag 'dont-show-again', 1, checked: nil
              = label_tag('dont-show-again') do
                Don't show me this again.
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Dismiss

app/views/shared/_midi_in.html.haml
.accordion-item#midi-input.hidden
  %h4.accordion-header Midi input
  .accordion-body.clearfix
    %select.form-control#midi-device
    %select.form-control#midi-channel
      %option Select MIDI Channel
      %option{value: -1} Any

      - (1..16).each do |number|
        %option{value: number}= "Channel #{number}"

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{'aria-controls' => 'navbar', 'aria-expanded' => 'false', 'data-target' => '#navbar', 'data-toggle' => 'collapse', :type => 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: '/'} VolcaShare
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Bass', '#', class: 'dropdown-toggle', id: 'dropdownMenuLink', data: { toggle: 'dropdown' }
          .dropdown-menu{ aria: { labelledby: 'dropdownMenuLink' } }
            %ul
              = link_to patches_path, class: 'dropdown-item' do
                %li Patches
              = link_to new_patch_path, class: 'dropdown-item' do
                %li New patch
              = link_to bass_emulator_path, class: 'dropdown-item' do
                %li Emulator
        %li
          = link_to 'Keys', '#', class: 'dropdown-toggle', id: 'dropdownMenuLink', data: { toggle: 'dropdown' }
          .dropdown-menu.keys{ aria: { labelledby: 'dropdownMenuLink' } }
            %ul
              = link_to keys_patches_path, class: 'dropdown-item' do
                %li Patches
              = link_to new_keys_patch_path, class: 'dropdown-item' do
                %li New patch
        - if current_page?(bass_emulator_path)
          %li
            = link_to 'Volca Bass Emulator', '#', class: 'link-like'
        - else
          %li
            = link_to 'Volca Bass Emulator', bass_emulator_path
        %li#emulator_nav_callout
          = link_to 'Volca Keys Emulator', keys_emulator_path
          .speech.left Brand new

        - if ENV['FEATURE_ENABLED_PATCH_NAMER'] == 'true'
          - if current_page?(synth_patch_namer_path)
            %li
              = link_to 'Synth Patch Namer', '#', class: 'link-like'
          - else
            %li#synth_patch_namer
              = link_to 'Synth Patch Namer', synth_patch_namer_path
              .speech.left New!
      %ul.nav.navbar-nav.navbar-right
        - if current_user.present?
          %li= link_to 'My Patches', user_path(current_user.slug)
          %li= link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Log in', new_user_session_path
          %li= link_to 'Sign Up', new_user_session_path
    / /.nav-collapse

app/views/shared/_patch_card.html.haml
- wrapper_class ||= ''
.wrapper.well.well-sm.patch-holder{ class: wrapper_class }
  .image-holder
    - if patch.user.present?
      = link_to user_patch_path(patch.user.slug, patch.slug) do
        .image.bass{ class: patch.index_classes }
    - else
      = link_to patch do
        .image.bass{ class: patch.index_classes }

  .patch
    - if patch.secret?
      .lock.glyph{ title: 'Secret' }
    - if patch.audio_sample_available?
      .speaker{ data: { oembed_url: "/oembed?user_slug=#{patch.user.slug}&slug=#{patch.slug}", toggle: 'modal', target: '#audio-preview-modal' }, title: 'Preview audio' }
    .title
      - if patch.user.present?
        = link_to patch.name, user_patch_path(patch.user.slug, patch.slug)
      - else
        = link_to patch.name, patch_path(patch.id)
    .info
      by
      - if patch.user.present?
        = link_to patch.username, user_path(patch.user.slug), { class: :username }
      - else
        ¯\_(ツ)_/¯
      %span.date= " on #{patch.created_at.strftime("%B %-d, %Y" )}"
      .icons
        - if current_user.present? && patch.user == current_user
          = link_to edit_patch_path(patch) do
            .edit.glyph
          = form_tag patch_path(patch),
            method: :delete,
            class: :delete_form,
            data: { confirm: 'Are you sure you want to delete that patch?' } do
            = submit_tag 'Delete', class: 'delete glyph'
    .description= patch.notes
    .tags
      - patch.tags.each do |tag|
        = link_to "\##{tag}", tags_show_path(tag: tag), class: :tag

app/views/shared/_patches.html.haml
- locals ||= {}
- if @patches.empty?
  .well No patches to show.
- else
  .col-sm-12.clearfix
    - unless locals[:hide_pagination]
      .pagination-holder.col-sm-6
        = paginate @patches
    .sort.col-sm-6
      .h4
        - audio_only = params[:audio_only] == 'true'
        - if @show_audio_filter
          = check_box_tag :audio_only, false, audio_only
          = label_tag 'audio_only', id: :audio_sample_label  do
            Has audio
            &nbsp;
            &nbsp;
        - if @sort.present?
          Sort by:
          - if @sort == :quality
            - if audio_only && @show_audio_filter
              = link_to 'Date Created', patches_path(sort: :newest, audio_only: true)
            - else
              = link_to 'Date Created', patches_path(sort: :newest)
          - else
            Date Created
          &nbsp;|&nbsp;
          - if @sort == :created_at
            - if audio_only && @show_audio_filter
              = link_to 'Quality', patches_path(audio_only: true)
            - else
              = link_to 'Quality', patches_path
          - else
            Quality

  - @patches.each do |patch|
    = render partial: 'shared/patch_card', locals: { patch: patch, wrapper_class: 'col-md-6' }

  .col-sm-12.clearfix
    - unless locals[:hide_pagination]
      .pagination-holder.col-sm-6
        = paginate @patches

app/views/shared/_randomize.html.haml
= link_to '', '#', id: :randomize, class: 'btn btn-primary', title: 'Randomize'